name: Deploy

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Requirement of https://github.com/marketplace/actions/generate-sitemap#requirements

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.8
      with:
        branch: gh-pages
        folder: deploy
        clean-exclude: "CNAME"

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://lyrcs.app/

    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
